import 'dart:async';
//import 'package:flutter/cupertino.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
const baseUrl = "http://192.168.0.191:7844";

class API {
  static Future getAnimes() async{
    var url = baseUrl + "/api/anime/";
    return await http.get(url);
  }
  
  static Future<String> getData() async{
    http.Response response =await http.get(
        Uri.encodeFull("http://192.168.0.191:7844/api/anime/"),
      headers:
      {
          "Accept": "application/json"
      },
    );
//    print(response.body);
    List data = json.decode(response.body);
    return data.toString(); // adicionado por mim
    //Autogenerated.fromJson(data[0]);
  }



}

//Future<Post> createPost(String url, {Map body}) async {
//  return http.post(url, body: body).then((http.Response response) {
//    final int statusCode = response.statusCode;
//
//    if (statusCode < 200 || statusCode > 400 || json == null) {
//      throw new Exception("Error while fetching data");
//    }
//    return Post.fromJson(json.decode(response.body));
//  });
//}
class GET
{
  static Future<http.Response> getRequest (senha, email) async {
    var url ='http://192.168.0.191:7844/api/User/';

    var data = {
      '\"Email\"':'\"$email\"',
      '\"Password\"': '\"$senha\"'
    };
    print(data);
    Uri uri = Uri.parse("http://192.168.0.191:7844/api/User/");
    final newUri = uri.replace(queryParameters: data);


    var response = await http.get(newUri);
    print(response.body);
    print(response.request);
//    print(response);
    return response;
  }
}
class POST
{
  static Future<http.Response> postRequest (nome, nick, senha, email) async {
    var url ='http://192.168.0.191:7844/api/User';

    Map data = {
      'Name': '$nome',
      'Nick': '$nick',
      'Password': '$senha',
      'Email': '$email',
    };
    //encode Map to JSON
    var body = json.encode(data);

    var response = await http.post(url,
        headers: {"Content-Type": "application/json"},
        body: body
    );
    print("${response.statusCode}");
    print("${response.body}");
    return response;
  }
}



